version: "3.8"
services:
  db:
    image: postgres
    container_name: spotdropping_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotdropping
      POSTGRES_PASSWORD: spotdropping
    volumes:
      - local_pgdata:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: spotdropping_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: